### ISSUE TITLE
点击process document后出现Error during document processing: 404 page not found 报错

### ISSUE THREAD

**Issue by shnulailai** [MeehanCole/mutil-models-test#1]
老师您好，我上传了自己的pdf后，在点击process document后报错Error during document processing: 404 page not found，请问这个是什么问题？怎么解决呢？
![image](https://github.com/user-attachments/assets/cd84fee1-82bb-418d-b965-0bc5af75dbf8)

**Comment by shnulailai** [comment]
后台报错：Adding 50 text elements to retriever...
Error during document processing: 404 page not found
2024-11-12 19:58:48.359 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

**Comment by MeehanCole** [comment]
@shnulailai 
# Initialize embedding model
        self.embeddings = OllamaEmbeddings(model="nomic-embed-text")  是不是这块模型没有搞？ 这块用的langchain封装ollama 的embed的接口

**Comment by shnulailai** [comment]
您的来信我已经收到了！

**Comment by shnulailai** [comment]
> @shnulailai
> 
> # Initialize embedding model
> ```
>     self.embeddings = OllamaEmbeddings(model="nomic-embed-text")  是不是这块模型没有搞？ 这块用的langchain封装ollama 的embed的接口
> ```

我把导入的包换成from langchain.embeddings import OllamaEmbeddings后可以成功运行了，有可能是我的ollama版本太低了0.1.48
